"""
Career Raider - Self-Healing: Git Operations
Creates Draft Pull Requests on GitHub via GitHub CLI (gh).
Never pushes to main directly.
"""
import os
import subprocess
import tempfile
from datetime import datetime

from src.config import get_settings
from src.logger import get_logger

log = get_logger("git_ops")
settings = get_settings()


def create_pr(patch_content: str, source_name: str) -> str:
    """
    1. Create a new branch  fix/auto-{source_name}-{timestamp}
    2. Apply the patch
    3. Commit + push
    4. Create Draft PR via gh CLI
    Returns the PR URL or empty string on failure.
    """
    github_token = settings.github_token
    github_repo = settings.github_repo

    if not github_token or not github_repo:
        log.warning("GITHUB_TOKEN or GITHUB_REPO not configured, skipping PR creation")
        return ""

    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch_name = f"fix/auto-{source_name.replace('_', '-')}-{timestamp}"
    pr_title = f"🤖 Auto-fix: {source_name} scraper (self-healing)"
    pr_body = (
        f"## Automated Self-Healing Fix\n\n"
        f"**Source**: `{source_name}`\n"
        f"**Generated**: {datetime.utcnow().isoformat()} UTC\n\n"
        f"### Patch Summary\n"
        f"This PR was auto-generated by the Career Raider anomaly detector. "
        f"The scraper for `{source_name}` returned 0 results and OpenHands "
        f"generated this fix.\n\n"
        f"### ⚠️ Review Carefully Before Merging\n"
        f"- Run the test suite\n- Verify selectors against the live site\n"
        f"- Check for unintended side effects\n\n"
        f"_Do not merge without human review._"
    )

    with tempfile.NamedTemporaryFile(mode="w", suffix=".diff", delete=False) as f:
        f.write(patch_content)
        patch_file = f.name

    env = os.environ.copy()
    env["GH_TOKEN"] = github_token
    env["GITHUB_TOKEN"] = github_token

    try:
        # Checkout new branch
        _run(["git", "checkout", "-b", branch_name])

        # Apply patch
        _run(["git", "apply", patch_file])

        # Stage and commit
        _run(["git", "add", "-A"])
        _run(["git", "commit", "-m", f"fix: auto-repair {source_name} scraper"])

        # Push to remote
        _run(["git", "push", "origin", branch_name], env=env)

        # Create Draft PR
        result = subprocess.run(
            ["gh", "pr", "create",
             "--draft",
             "--title", pr_title,
             "--body", pr_body,
             "--repo", github_repo,
             "--head", branch_name,
             "--base", "main"],
            capture_output=True, text=True, env=env,
        )

        if result.returncode == 0:
            pr_url = result.stdout.strip()
            log.info("Draft PR created", url=pr_url, branch=branch_name)
            return pr_url
        else:
            log.error("gh pr create failed", stderr=result.stderr)
            return ""

    except Exception as e:
        log.error("create_pr error", error=str(e))
        return ""
    finally:
        os.unlink(patch_file)
        # Return to main
        try:
            _run(["git", "checkout", "main"])
        except Exception:
            pass


def _run(cmd: list, env: dict = None, cwd: str = ".") -> subprocess.CompletedProcess:
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, env=env)
    if result.returncode != 0:
        raise RuntimeError(f"Command {cmd} failed: {result.stderr}")
    return result
