"""
Career Raider - Self-Healing: Incident Logger
Captures deep context on crashes and formats them for OpenHands.
"""
import os
import sys
import hashlib
import traceback
from datetime import datetime
from typing import Optional, Dict, Any

import redis as redis_lib

from src.logger import get_logger
from src.config import get_settings

log = get_logger("incident_logger")

INCIDENTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../..", "logs", "incidents"))
os.makedirs(INCIDENTS_DIR, exist_ok=True)

# Cooldown to prevent OpenHands from being invoked multiple times for the exact same error
INCIDENT_COOLDOWN_SECONDS = 3600  # 1 hour


def _get_redis() -> redis_lib.Redis:
    settings = get_settings()
    return redis_lib.from_url(settings.redis_url, decode_responses=True)


def _hash_exception(exc_type: type, exc_value: BaseException, tb) -> str:
    """Generate a unique fingerprint for an exception type + location."""
    # Hash the exception type and the last frame of the traceback (where it occurred)
    tb_str = "".join(traceback.format_exception_only(exc_type, exc_value))
    if tb:
        last_frame = traceback.extract_tb(tb)[-1]
        tb_str += f"{last_frame.filename}:{last_frame.lineno}"
    return hashlib.md5(tb_str.encode()).hexdigest()


def log_incident(
    context_name: str,
    exc_info: Optional[tuple] = None,
    extra_context: Optional[Dict[str, Any]] = None
) -> tuple[str, bool]:
    """
    Generate an incident report for an error.
    Returns:
        tuple(incident_path: str, should_trigger_openhands: bool)
    """
    if exc_info is None:
        exc_info = sys.exc_info()

    exc_type, exc_value, exc_tb = exc_info
    if exc_type is None:
        log.warning("log_incident called without an active exception")
        return "", False

    # Extract structured context if it's a CareerRaiderError
    if hasattr(exc_value, "extra_context") and isinstance(exc_value.extra_context, dict):
        if extra_context is None:
            extra_context = {}
        # Merge, giving precedence to explicitly passed extra_context
        merged_context = {**exc_value.extra_context, **extra_context}
        extra_context = merged_context

    error_hash = _hash_exception(exc_type, exc_value, exc_tb)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    incident_filename = f"incident_{context_name}_{timestamp}_{error_hash[:8]}.md"
    incident_path = os.path.join(INCIDENTS_DIR, incident_filename)

    # Format the traceback
    tb_str = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))

    # Try to extract local variables from the last frame if available
    locals_str = ""
    if exc_tb:
        curr_tb = exc_tb
        while curr_tb.tb_next:
            curr_tb = curr_tb.tb_next
        local_vars = curr_tb.tb_frame.f_locals
        locals_str = "### Local Variables (Last Frame)\n```python\n"
        for k, v in local_vars.items():
            try:
                val_str = str(v)[:500]  # truncate huge strings
                locals_str += f"{k} = {val_str}\n"
            except Exception:
                locals_str += f"{k} = <unrepresentable>\n"
        locals_str += "```\n"

    # Format extra context
    extra_str = ""
    if extra_context:
        extra_str = "### Extra Context\n```json\n"
        import json
        try:
            extra_str += json.dumps(extra_context, indent=2, default=str)
        except Exception:
            extra_str += str(extra_context)
        extra_str += "\n```\n"

    # Build markdown report
    report = (
        f"# Incident Report: {context_name}\n"
        f"**Timestamp:** {datetime.utcnow().isoformat()}Z\n"
        f"**Error Hash:** {error_hash}\n"
        f"**Exception Type:** {exc_type.__name__}\n"
        f"**Error Message:** {str(exc_value)}\n\n"
        f"## Traceback\n```python\n{tb_str}```\n\n"
        f"{locals_str}\n"
        f"{extra_str}\n"
        f"--- Generated by Career Raider Auto-Diagnostic System ---"
    )

    with open(incident_path, "w") as f:
        f.write(report)
    
    log.error("Incident logged", context=context_name, incident_path=incident_path, error_hash=error_hash)

    # Check cooldown to decide if we should trigger OpenHands
    should_trigger = False
    try:
        r = _get_redis()
        cooldown_key = f"incident_cooldown:{error_hash}"
        # setnx returns 1 if key was set, 0 if it already existed
        if r.setnx(cooldown_key, "1"):
            r.expire(cooldown_key, INCIDENT_COOLDOWN_SECONDS)
            should_trigger = True
            log.info("New critical error detected. Triggering OpenHands.", error_hash=error_hash)
        else:
            log.info("Error in cooldown. Skipping OpenHands trigger.", error_hash=error_hash)
    except Exception as e:
        log.warning("Redis unavailable for cooldown check", error=str(e))
        # Default to True if Redis fails, patch_generator can handle it, though it might spam if we're not careful.
        # But wait, to be safe, if Redis is down we probably shouldn't spam OpenHands.
        should_trigger = False

    return incident_path, should_trigger
